# Generated by Django 3.0.6 on 2020-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='name')),
                ('telefone', models.CharField(max_length=150, verbose_name='telefone')),
                ('observacao', models.CharField(max_length=150, verbose_name='observacoes')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
            ],
        ),
    ]
