# Generated by Django 3.0.6 on 2020-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='observacao',
        ),
        migrations.AddField(
            model_name='formulario',
            name='descricao',
            field=models.TextField(default='string', max_length=550, verbose_name='descricao'),
        ),
    ]
