# Generated by Django 3.0.6 on 2020-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200514_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='telefone',
            field=models.CharField(max_length=50, verbose_name='telefone'),
        ),
    ]
