# Generated by Django 3.0.6 on 2020-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200514_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='name')),
                ('telefone', models.CharField(max_length=50, verbose_name='telefone')),
                ('descricao', models.TextField(default='string', max_length=550, verbose_name='descricao')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
            ],
        ),
    ]
