# Generated by Django 3.0.6 on 2020-05-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_curriculo_curriculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='', verbose_name='curriculo'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='email'),
        ),
    ]
