# Generated by Django 3.0.6 on 2020-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200515_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='curriculo',
            field=models.FileField(upload_to='ebaranowski/Downloads/', verbose_name='curriculo'),
        ),
    ]
