# Generated by Django 3.0.6 on 2020-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200515_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='curriculo',
            field=models.FileField(upload_to='media/', verbose_name='curriculo'),
        ),
    ]
