# Generated by Django 3.0.6 on 2020-05-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200515_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='media/', verbose_name='curriculo'),
        ),
    ]
